version: '3.1'

services:
    fn:
      image: fnproject/functions
      restart: always
      privileged: true
      links:
         - db
      environment:
              - DB_URL=postgres://funcs:funcs@db/funcs?sslmode=disable
              - MQ_URL=redis://redis:6379
              - ZIPKIN_URL=http://zipkin:9411/api/v1/spans
      ports:
           - 8080:8080
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
           - db
           - redis
           
    fn-ui:
      image: fnproject/ui
      restart: always
      ports:
           - 5000:4000
      environment:
            - API_URL=http://fn:8080
      links:
            - fn
    db:
      image: postgres:10
      restart: always
      environment:
            POSTGRES_PASSWORD: funcs
            POSTGRES_USER: funcs
            POSTGES_DB: funcs
    adminer:
        image: adminer
        restart: always
        ports:
           - 18080:8080
        depends_on:
           - db
      
    zipkin:      
      image: openzipkin/zipkin
      ports:
           - 9411:9411
      depends_on:
          - fn
 
    redis:
        image: redis
        restart: always
    prometheus:
        image: prom/prometheus
        ports:
          - 9090:9090
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
        depends_on:
           - fn
    grafana:
        image: grafana/grafana
        links:
           - fn
        ports:
           - 3000:3000
        environment:
           - GF_SERVER_ROOT_URL=http://localhost
           - GF_SECURITY_ADMIN_PASSWORD=secret

           - 8080:8080
        depends_on:
           - prometheus
   
    portainer:
        image: portainer/portainer:1.15.0
        privileged: true
        ports:
           - 9000:9000
        volumes:
            - ./portainer-data:/data
            - /var/run/docker.sock:/var/run/docker.sock

